spring:
  application:
    name: jw-registry
server:
  port: 10086
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
